forge_support: false
online_mode: true
log_commands: true
listeners:
- query_port: 25577
  motd: '&8» &7github.com/anweisen/&e&lMinecraftCloud'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - fallback
  default_server: fallback
  fallback_server: fallback
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: false
connection_throttle: 0
groups:
  anweisen:
  - admin
log_pings: true
ip_forward: true
prevent_proxy_connections: false
network_compression_threshold: 256
stats: e65ec8da-7f35-4741-a904-9b1dfcf138d6
disabled_commands:
- disabledcommandhere
timeout: 30000
permissions:
  default: []
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - reportsystem.goto
  - reportsystem.show
servers:
  fallback:
    motd: '&7Just another Server &8| &c&lForced Host'
    address: localhost:12345
    restricted: false
player_limit: -1
