name: Cloud-Perms
author: anweisen
version: 1.0
main: net.anweisen.cloud.modules.perms.bukkit.BukkitCloudPermsPlugin
description: Runtime module to enable the use of an integrated permission system
website: https://github.com/anweisen/DyCloud
api-version: 1.13
