name: Cloud-Bridge
author: anweisen
version: 1.0
main: net.anweisen.cloud.modules.bridge.bukkit.BukkitCloudBridgePlugin
description: Runtime module to enable the use of player management possible
website: https://github.com/anweisen/DyCloud
api-version: 1.13
